* ChiME

This is a framework for computing the two body matrix elements, reduced in total
angular momentum and isospin spaces, of electroweak operators in the 3D harmonic
oscillator basis.

** Requirements
ChiME depends on several libraries as follows:
  - [[https://github.com/e-eight/quadpp][quadpp]]
  - [[https://github.com/e-eight/basis_func/][basis_func]]
  - [[https://www.gnu.org/software/gsl/][GNU Scientific Library (v. 2.6)]]
  - [[http://eigen.tuxfamily.org/index.php?title=Main_Page][Eigen (v. 3.3.7)]]
  - [[https://github.com/e-eight/basis.git][basis]]
  - [[https://github.com/e-eight/am.git][am]]
  - [[https://github.com/e-eight/am.git][mcutils]]
The code is written in C++14. You will need a compiler that supports that.

** Compilation

** Usage

** Contributors
  - Soham Pal (Developed the original C version. Theory and lead code developer.)
  - Robert Basili (Ported the original C version to C++. Tester.)
  - Shiplu Sarker (Theory developer.)

** License
ChiME is licensed under the MIT license (see =LICENSE= for details). The libraries
that ChiME depends on may have different licenses. Please check those project for
further details about their licenses.
