* ChiME

This is a framework for computing the two body matrix elements, reduced in total
angular momentum and isospin spaces, of electroweak operators in the 3D harmonic
oscillator basis.

** Requirements
=ChiME= depends on the following libraries:
  - [[https://www.gnu.org/software/gsl/][GNU Scientific Library (v. 2.6)]]
  - [[http://eigen.tuxfamily.org/index.php?title=Main_Page][Eigen (v. 3.3.7)]]
  - [[https://github.com/e-eight/quadpp][quadpp]]  (submodule)
  - [[https://github.com/e-eight/basis_func/][basis_func]] (submodule)
  - [[https://github.com/e-eight/basis.git][basis]] (submodule)
  - [[https://github.com/e-eight/am.git][am]] (submodule)
  - [[https://github.com/e-eight/am.git][mcutils]] (submodule)
The code is written in C++14. You will need a compiler that supports that.

** Compilation
The best way to obtain =ChiME= is to clone this repository, and update the
submodules:
#+BEGIN_SRC shell
git clone https://github.com/e-eight/chime.git
cd chime
git submodule update --init --recursive
#+END_SRC

That will clone the submodule libraries that =ChiME= depends on and also the
=config= libraries. To compile do the following from inside the chime directory:
#+BEGIN_SRC shell
ln -s config/ndconfig/config-gnu.mk ./config.mk
ln -s config/ndmakefile/makefile ./
make relativecm-gen # or make relative-gen for relative operators
#+END_SRC
The =ndconfig= repository contains configuration files for different compilers
and environments. For more details about which configuration would be right for
your purpose please check [[https://github.com/nd-nuclear-theory/ndconfig/blob/master/INSTALL.md][ndconfig installation instructions]]. The binaries will
be located inside the =programs= directory.

** Usage
=relativecm-gen= reads in the input file =relcm.in=, and =relative-gen= reads
the input file =relative.in=. For the details about how to construct the input
files, please check the headers of =relativecm-gen.cpp=, and =relative-gen.cpp=.

** Contributors
  - Soham Pal (Developed the original C version. Theory and lead code
    developer.)
  - Robert Basili (Ported the original C version to C++. Tester.)
  - Shiplu Sarker (Theory developer.)

** License
ChiME is licensed under the MIT license (see =LICENSE= for details). The
libraries that ChiME depends on may have different licenses. Please check those
project for further details about their licenses.
